config/routes.rb
Rails.application.routes.draw do
  resources :kidneys
  devise_for :users

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kidney.rb
class Kidney < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/kidneys_controller.rb
class KidneysController < ApplicationController
  before_action :set_kidney, only: [:show, :edit, :update, :destroy]

  # GET /kidneys
  # GET /kidneys.json
  def index
    @kidneys = Kidney.all
  end

  # GET /kidneys/1
  # GET /kidneys/1.json
  def show
  end

  # GET /kidneys/new
  def new
    @kidney = Kidney.new
  end

  # GET /kidneys/1/edit
  def edit
  end

  # POST /kidneys
  # POST /kidneys.json
  def create
    @kidney = Kidney.new(kidney_params)

    respond_to do |format|
      if @kidney.save
        format.html { redirect_to @kidney, notice: 'Kidney was successfully created.' }
        format.json { render :show, status: :created, location: @kidney }
      else
        format.html { render :new }
        format.json { render json: @kidney.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kidneys/1
  # PATCH/PUT /kidneys/1.json
  def update
    respond_to do |format|
      if @kidney.update(kidney_params)
        format.html { redirect_to @kidney, notice: 'Kidney was successfully updated.' }
        format.json { render :show, status: :ok, location: @kidney }
      else
        format.html { render :edit }
        format.json { render json: @kidney.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kidneys/1
  # DELETE /kidneys/1.json
  def destroy
    @kidney.destroy
    respond_to do |format|
      format.html { redirect_to kidneys_url, notice: 'Kidney was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kidney
      @kidney = Kidney.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kidney_params
      params.require(:kidney).permit(:name, :value, :description, :blood_group, :fresh_harvest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kidneys_helper.rb
module KidneysHelper
end

app/views/home/index.html.erb
<h1> Kidneys rental main page </h1>

app/views/kidneys/_form.html.erb
<%= form_with(model: kidney, local: true) do |form| %>
  <% if kidney.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kidney.errors.count, "error") %> prohibited this kidney from being saved:</h2>

      <ul>
      <% kidney.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :blood_group %>
    <%= form.text_field :blood_group %>
  </div>

  <div class="field">
    <%= form.label :fresh_harvest %>
    <%= form.check_box :fresh_harvest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kidneys/edit.html.erb
<h1>Editing Kidney</h1>

<%= render 'form', kidney: @kidney %>

<%= link_to 'Show', @kidney %> |
<%= link_to 'Back', kidneys_path %>

app/views/kidneys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kidneys</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th>Description</th>
      <th>Blood group</th>
      <th>Fresh harvest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kidneys.each do |kidney| %>
      <tr>
        <td><%= kidney.name %></td>
        <td><%= kidney.value %></td>
        <td><%= kidney.description %></td>
        <td><%= kidney.blood_group %></td>
        <td><%= kidney.fresh_harvest %></td>
        <td><%= link_to 'Show', kidney %></td>
        <td><%= link_to 'Edit', edit_kidney_path(kidney) %></td>
        <!-- <td><%= link_to 'Destroy', kidney, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kidney', new_kidney_path %>

app/views/kidneys/new.html.erb
<h1>New Kidney</h1>

<%= render 'form', kidney: @kidney %>

<%= link_to 'Back', kidneys_path %>

app/views/kidneys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kidney.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @kidney.value %>
</p>

<p>
  <strong>Description:</strong>
  <%= @kidney.description %>
</p>

<p>
  <strong>Blood group:</strong>
  <%= @kidney.blood_group %>
</p>

<p>
  <strong>Fresh harvest:</strong>
  <%= @kidney.fresh_harvest %>
</p>

<%= link_to 'Edit', edit_kidney_path(@kidney) %> |
<%= link_to 'Back', kidneys_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KidneysRental</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main_page">
      <%= render_navigation if user_signed_in? %>

      <%= yield %>
    </div>
  </body>
</html>